### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by arosen93** [flintlib/python-flint#24]
When trying to `pip install` python-flint, it fails if you don't have `Cython` or `numpy` installed. This should be added to the required packages.

**Comment by oscarbenjamin** [comment]
I am not sure how to do this from within `setup.py`. I think that it requires moving from `setup.py` to `pyproject.toml` which also then requires choosing a build backend. There are a few related problems in making that change in python-flint.

For now as a workaround you should install Cython and numpy and use `--no-build-isolation` as described in the README:
```
pip install 'cython>=3' numpy
pip install --no-build-isolation python-flint
```
On Windows or OSX this is not necessary because `pip install python-flint` will install precompiled binaries.

I'm going to close this issue in favour of gh-52 which describes in more detail what needs to be done.
