### ISSUE TITLE
`pow(int, int, fmpz)` is always 1

### ISSUE THREAD

**Issue by haru-44** [flintlib/python-flint#92]
In `python-flint==0.4.4`.

```python
>>> from flint import fmpz
>>> pow(2, 5, 1000)
32
>>> pow(2, 5, fmpz(1000))
1
>>> pow(2, fmpz(5), fmpz(1000))
32
```

**Comment by oscarbenjamin** [comment]
Looks like the code here should be checking the type of `s`:
https://github.com/flintlib/python-flint/blob/98c28837e48c623ff24d9e7c2e4994e88500a310/src/flint/types/fmpz.pyx#L362-L371
I hadn't contemplated that `__pow__(s, t, m)` might be called with `s` not being an `fmpz`. At this line `s` will be an `int` (`PyLong`):
https://github.com/flintlib/python-flint/blob/98c28837e48c623ff24d9e7c2e4994e88500a310/src/flint/types/fmpz.pyx#L405
Presumably the bytes there look like a 1 as an fmpz_t.

The fix is that the s argument should be handled in the same way as the t argument.

**Comment by oscarbenjamin** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by haru-44** [comment]
Thanks for the correction.
